export const categories = [
  { id: "all", name: "All", icon: "Grid3X3" },
  { id: "rice", name: "Rice Dishes", icon: "Wheat" },
  { id: "swallow", name: "Swallows", icon: "Circle" },
  { id: "soup", name: "Soups", icon: "Soup" },
  { id: "protein", name: "Proteins", icon: "Beef" },
  { id: "snacks", name: "Snacks", icon: "Cookie" },
  { id: "drinks", name: "Drinks", icon: "Coffee" },
  { id: "breakfast", name: "Breakfast", icon: "Sun" },
];

export const foodItems = [
  {
    id: "1",
    name: "Jollof Rice Special",
    description: "Premium long-grain rice cooked in rich tomato stew with authentic Nigerian spices, served with fried plantain",
    price: 4500,
    category: "rice",
    image: "https://images.unsplash.com/photo-1662116765994-54592f7e2d35?w=800&q=80",
    rating: 4.8,
    reviews: 328,
    prepTime: "25-30 mins",
    calories: 650,
    isPopular: true,
    isAvailable: true,
    tags: ["spicy", "best-seller"],
  },
  {
    id: "2",
    name: "Fried Rice Supreme",
    description: "Stir-fried rice with mixed vegetables, scrambled eggs, and shrimp",
    price: 5000,
    category: "rice",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb74b?w=800&q=80",
    rating: 4.7,
    reviews: 256,
    prepTime: "25-30 mins",
    calories: 580,
    isPopular: true,
    isAvailable: true,
    tags: ["contains-shrimp"],
  },
  {
    id: "3",
    name: "Native Rice (Ofada)",
    description: "Authentic Ofada rice served with special ayamase sauce and assorted meat",
    price: 5500,
    category: "rice",
    image: "https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=800&q=80",
    rating: 4.9,
    reviews: 189,
    prepTime: "30-35 mins",
    calories: 720,
    isPopular: true,
    isAvailable: true,
    tags: ["spicy", "traditional"],
  },
  {
    id: "4",
    name: "Pounded Yam",
    description: "Smooth, fluffy pounded yam made from selected yam tubers, perfect with any soup",
    price: 2000,
    category: "swallow",
    image: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800&q=80",
    rating: 4.9,
    reviews: 567,
    prepTime: "15 mins",
    calories: 380,
    isPopular: true,
    isAvailable: true,
    tags: ["traditional", "premium"],
  },
  {
    id: "5",
    name: "Eba (Garri)",
    description: "Smooth cassava flakes prepared to perfection, served hot",
    price: 500,
    category: "swallow",
    image: "https://images.unsplash.com/photo-1626202158825-4b0962e2fdd5?w=800&q=80",
    rating: 4.7,
    reviews: 892,
    prepTime: "10 mins",
    calories: 320,
    isPopular: false,
    isAvailable: true,
    tags: ["affordable"],
  },
  {
    id: "6",
    name: "Egusi Soup",
    description: "Rich melon seed soup cooked with spinach, assorted meat, and smoked fish",
    price: 3500,
    category: "soup",
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80",
    rating: 4.9,
    reviews: 678,
    prepTime: "35-40 mins",
    calories: 420,
    isPopular: true,
    isAvailable: true,
    tags: ["best-seller", "protein-rich"],
  },
  {
    id: "7",
    name: "Vegetable Soup",
    description: "Fresh spinach and waterleaf cooked with palm oil and assorted meat",
    price: 3200,
    category: "soup",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
    rating: 4.7,
    reviews: 445,
    prepTime: "30 mins",
    calories: 280,
    isPopular: true,
    isAvailable: true,
    tags: ["healthy"],
  },
  {
    id: "8",
    name: "Ogbono Soup",
    description: "Draw soup made from wild mango seeds with assorted meat and fish",
    price: 3500,
    category: "soup",
    image: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800&q=80",
    rating: 4.8,
    reviews: 389,
    prepTime: "35 mins",
    calories: 380,
    isPopular: true,
    isAvailable: true,
    tags: ["draw-soup"],
  },
  {
    id: "9",
    name: "Grilled Chicken",
    description: "Tender chicken marinated in special spices and grilled to perfection",
    price: 3500,
    category: "protein",
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800&q=80",
    rating: 4.7,
    reviews: 423,
    prepTime: "25 mins",
    calories: 280,
    isPopular: true,
    isAvailable: true,
    tags: ["grilled"],
  },
  {
    id: "10",
    name: "Suya",
    description: "Spicy grilled beef skewers with peanut spice blend",
    price: 1500,
    category: "protein",
    image: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&q=80",
    rating: 4.8,
    reviews: 892,
    prepTime: "15 mins",
    calories: 240,
    isPopular: true,
    isAvailable: true,
    tags: ["spicy", "street-food"],
  },
  {
    id: "11",
    name: "Meat Pie",
    description: "Flaky pastry filled with seasoned minced meat and vegetables",
    price: 800,
    category: "snacks",
    image: "https://images.unsplash.com/photo-1621993202323-c430e75b2f5f?w=800&q=80",
    rating: 4.6,
    reviews: 445,
    prepTime: "15 mins",
    calories: 280,
    isPopular: true,
    isAvailable: true,
    tags: ["baked"],
  },
  {
    id: "12",
    name: "Puff Puff",
    description: "Sweet, fluffy deep-fried dough balls (5 pieces)",
    price: 500,
    category: "snacks",
    image: "https://images.unsplash.com/photo-1626202158825-4b0962e2fdd5?w=800&q=80",
    rating: 4.7,
    reviews: 567,
    prepTime: "10 mins",
    calories: 180,
    isPopular: true,
    isAvailable: true,
    tags: ["sweet"],
  },
  {
    id: "13",
    name: "Akara",
    description: "Crispy fried bean cakes made from peeled black-eyed peas (4 pieces)",
    price: 600,
    category: "snacks",
    image: "https://images.unsplash.com/photo-1626202158825-4b0962e2fdd5?w=800&q=80",
    rating: 4.5,
    reviews: 334,
    prepTime: "15 mins",
    calories: 160,
    isPopular: true,
    isAvailable: true,
    tags: ["protein-rich"],
  },
  {
    id: "14",
    name: "Zobo Drink",
    description: "Refreshing hibiscus drink with ginger and pineapple (500ml)",
    price: 500,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&q=80",
    rating: 4.7,
    reviews: 445,
    prepTime: "0 mins",
    calories: 80,
    isPopular: true,
    isAvailable: true,
    tags: ["healthy", "refreshing"],
  },
  {
    id: "15",
    name: "Chapman",
    description: "Classic Nigerian mocktail with grenadine, orange, and cucumber",
    price: 1200,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&q=80",
    rating: 4.8,
    reviews: 334,
    prepTime: "5 mins",
    calories: 140,
    isPopular: true,
    isAvailable: true,
    tags: ["mocktail"],
  },
  {
    id: "16",
    name: "Full Breakfast",
    description: "Boiled yam/plantain with egg sauce, sausages, and baked beans",
    price: 4500,
    category: "breakfast",
    image: "https://images.unsplash.com/photo-1533089862017-5614ecb352ae?w=800&q=80",
    rating: 4.7,
    reviews: 234,
    prepTime: "20 mins",
    calories: 580,
    isPopular: true,
    isAvailable: true,
    tags: ["hearty"],
  },
  {
    id: "17",
    name: "Bread & Egg",
    description: "Fresh sliced bread with scrambled eggs and tomato sauce",
    price: 2500,
    category: "breakfast",
    image: "https://images.unsplash.com/photo-1525351484163-7529414395d8?w=800&q=80",
    rating: 4.5,
    reviews: 445,
    prepTime: "15 mins",
    calories: 380,
    isPopular: true,
    isAvailable: true,
    tags: ["quick"],
  },
  {
    id: "18",
    name: "Yam Porridge",
    description: "Spicy yam porridge cooked with palm oil, spinach, and smoked fish",
    price: 3000,
    category: "breakfast",
    image: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800&q=80",
    rating: 4.8,
    reviews: 312,
    prepTime: "25 mins",
    calories: 420,
    isPopular: true,
    isAvailable: true,
    tags: ["spicy", "filling"],
  },
];

export const testimonials = [
  {
    id: "1",
    name: "Adeola Williams",
    role: "Regular Customer",
    content: "FOOD 101 has the best Jollof Rice in Ilorin! The delivery is always on time and the food arrives hot.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    date: "2024-03-15",
  },
  {
    id: "2",
    name: "Emmanuel Okafor",
    role: "Student, Unilorin",
    content: "As a student living near UITH, FOOD 101 is a lifesaver. Affordable prices and great food!",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    date: "2024-03-10",
  },
  {
    id: "3",
    name: "Fatima Abdullahi",
    role: "Medical Resident",
    content: "Working at UITH means long hours. FOOD 101 delivers quality meals even during night shifts.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    date: "2024-03-08",
  },
];

export const orderStatuses = [
  { id: "pending", label: "Order Placed", description: "Your order has been received", color: "text-yellow-500", bgColor: "bg-yellow-500/10" },
  { id: "confirmed", label: "Confirmed", description: "Restaurant is preparing your meal", color: "text-blue-500", bgColor: "bg-blue-500/10" },
  { id: "preparing", label: "Preparing", description: "Chef is cooking your meal", color: "text-orange-500", bgColor: "bg-orange-500/10" },
  { id: "ready", label: "Ready", description: "Your order is ready", color: "text-purple-500", bgColor: "bg-purple-500/10" },
  { id: "out-for-delivery", label: "On the Way", description: "Rider is heading to you", color: "text-indigo-500", bgColor: "bg-indigo-500/10" },
  { id: "delivered", label: "Delivered", description: "Enjoy your meal!", color: "text-green-500", bgColor: "bg-green-500/10" },
];

export const howItWorks = [
  { step: 1, title: "Browse Menu", description: "Explore our variety of authentic Nigerian dishes", icon: "Search", color: "from-orange-500 to-red-500" },
  { step: 2, title: "Place Order", description: "Add meals to cart and checkout securely", icon: "ShoppingCart", color: "from-red-500 to-pink-500" },
  { step: 3, title: "Track Delivery", description: "Watch your order progress in real-time", icon: "MapPin", color: "from-pink-500 to-purple-500" },
  { step: 4, title: "Enjoy Meal", description: "Receive your hot, fresh meal", icon: "Utensils", color: "from-purple-500 to-indigo-500" },
];

export const businessInfo = {
  name: "FOOD 101",
  tagline: "Delicious Meals, Delivered Fast",
  location: "Opposite UITH, Ilorin, Kwara State, Nigeria",
  phone: "+234 803 123 4567",
  email: "hello@food101.ng",
  hours: { weekdays: "7:00 AM - 10:00 PM", weekends: "8:00 AM - 11:00 PM" },
  delivery: { fee: 500, minOrder: 2000, estimatedTime: "25-45 mins" },
};

export const getPopularItems = () => foodItems.filter(item => item.isPopular);
export const getItemsByCategory = (categoryId) => categoryId === "all" ? foodItems : foodItems.filter(item => item.category === categoryId);
export const getItemById = (id) => foodItems.find(item => item.id === id);
export const searchItems = (query) => {
  const lowercaseQuery = query.toLowerCase();
  return foodItems.filter(item =>
    item.name.toLowerCase().includes(lowercaseQuery) ||
    item.description.toLowerCase().includes(lowercaseQuery)
  );
};

export function formatPrice(price) {
  return new Intl.NumberFormat("en-NG", {
    style: "currency",
    currency: "NGN",
    minimumFractionDigits: 0,
  }).format(price);
}

export function generateOrderId() {
  return `FD${Date.now().toString(36).toUpperCase()}${Math.random().toString(36).substring(2, 5).toUpperCase()}`;
}
